environment:
  nodejs_version: "20"

branches:
  only:
    - master  # ветка git
    - main

cache: node_modules  # кеширование

install:
  - npm install  # команда установки зависимостей

build: on # отключаем встроенную в appveyor систему сборки

test_script:
  - npm run lint && npm test  # скрипт тестирования